permalink   : /:categories/:title/
markdown    : kramdown
highlighter : pygments

paginate: 2 #6
# comments: true
paginate_path: "/page/:num"

baseurl: "" # change to empty string ""
domain_name: diablowu.com
timezone: "Asia/Shanghai"
encoding: utf-8
# google_analytics: UA-52446115-1

# source:      source
# destination: _site

# cover: /assets/images/header-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: 我是大菠萝
title: 我是大菠萝 | 博客博客博客博客
description: "我是一个混在IT圈有点艺术气质的文艺酷爸爸，疯狂的NFL铁粉，绿湾包装工的奶酪头"
meta_description: "Desenvolvedor Front-end/Wordpress, Design Responsivo, HTML5, CSS3 e JavaScript"
meta_keywords: "technology, nfl, docker, nodejs, python, java, raspberrypi, angularjs, arduino"
url: http://diablowu.com
production_url: http://diablowu.com
# repo: https://github.com/nandomoreirame/nandomoreira-jekyll-theme
# disqus_shortname: "fernandomoreira"
# rss_path: 
author:
  name      : Diablo Wu
  image     : "http://www.gravatar.com/avatar/ff39a8987dc515c069b7bb8127dccde6.jpg?s=500"
  email     : wubo19842008@gmail.com
  url       : http://diablowu.com
  twitter   : http://twitter.com/diablowu
  weixin    : iamdiablo
  github    : http://github.com/diablowu
  linkedin  : https://cn.linkedin.com/in/diablowu
  bio       : "Talk is cheap. Show me the code."


# Plugin: jekyll-assets
assets:
  dirname: /assets
  baseurl: /assets/ # change to /assets/
  sources:
    - assets/images
    - assets/fonts
    - assets/css
    - assets/js
  cache: true
  gzip: [ text/css, application/javascript ]

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: all

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]


# host server
host: "0.0.0.0"

# 七牛云存储配置
qnimgurl: http://dbimg.u.qiniudn.com/img/
qnfileurl: http://dbimg.u.qiniudn.com/file/


gravatar: 